base_url = "https://swapi.co/api/"
char_endpoint = "people/"
film_endpoint = "films/"
species_endpoint = "species/"
vech_endpoint = "vehicles/"
ships_endpoint = "starships/"
planets_endpoint = "planets/"
